language: android
android:
  components:
    - tools
    - build-tools-19.1.0
    - android-19
    - platform-tools
before_script:
  - chmod +x gradlew
after_success:
  - chmod 600 .travis/travis
  - eval `ssh-agent -s`
  - ssh-add .travis/travis
  - mv app/build/outputs/apk apk
  - git add apk
  - git commit -am "deploy"
  - git remote add deploy git@github.com:typeetfunc/project_2015_01.git
  - git push deploy