language: android
android:
  components:
  - tools
  - build-tools-19.1.0
  - android-19
  - platform-tools
before_script:
  - chmod +x gradlew
after_success:
  - mv app/build/outputs/apk apk
  - ls apk
  - git config --global user.email "travis@ci.org"
  - git config --global user.name "travis"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add apk
  - git commit -m "deploy"
  - git push origin master
env:
  global:
    secure: VDFChfnxB0X9U/TCmqd4PAmyW1gEqaetqfYqMiChPVeVkNfCrKXpO7s6kdwFGV6iG+5DBiyvVtuKOQwSXCjc551DORD6QegrFX5asU7ZMhFsmF2dtfh0pkjo9AENpcfwrzIx9zu+iqFwQq4SKbAYGBBzuuScg7uuHcZvpUIuCnU=
