language: android
android:
  components:
    - tools
    - build-tools-19.1.0
    - android-19
    - platform-tools
before_script:
  - chmod +x gradlew
after_success:
  - mv app/build/outputs/apk apk
  - ls apk
  - git config --global user.email "travis@ci.org"
  - git config --global user.name "travis"
  - git add apk
  - git remote add deploy https://github.com/typeetfunc/project_2015_01.git
  - git commit -m "deploy"
  - git push deploy master