language: android
android:
  components:
  - tools
  - build-tools-21.0.0
  - android-21
  - platform-tools
before_script:
  - chmod +x gradlew
after_success: 
  - git config --global user.email "travis@ci.org"
  - git config --global user.name "travis"
  - git clone -b deploy "https://github.com/typeetfunc/project_2015_01.git" apk
  - cp -rf app/build/outputs/apk/* apk
  - cd apk
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add .
  - git commit -m "deploy from travis-ci"
  - git push origin deploy
branches:
  only:
    - master 
env:
  global:
    secure: VDFChfnxB0X9U/TCmqd4PAmyW1gEqaetqfYqMiChPVeVkNfCrKXpO7s6kdwFGV6iG+5DBiyvVtuKOQwSXCjc551DORD6QegrFX5asU7ZMhFsmF2dtfh0pkjo9AENpcfwrzIx9zu+iqFwQq4SKbAYGBBzuuScg7uuHcZvpUIuCnU=
